name: imagelab  # Add this line
description: "A new Flutter project."

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0  # Add this line

flutter:
  uses-material-design: true
